// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type Todo struct {
	ID          int64  `json:"id"`
	Owner       string `json:"owner"`
	Title       string `json:"title"`
	Category    string `json:"category"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
}
