// Code generated by sqlc. DO NOT EDIT.
// source: todo.sql

package db

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    "owner",
    "title",
    "category",
    "description",
    "completed"
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, owner, title, category, description, completed
`

type CreateTodoParams struct {
	Owner       string         `json:"owner"`
	Title       string         `json:"title"`
	Category    string         `json:"category"`
	Description sql.NullString `json:"description"`
	Completed   bool           `json:"completed"`
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Owner,
		arg.Title,
		arg.Category,
		arg.Description,
		arg.Completed,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Title,
		&i.Category,
		&i.Description,
		&i.Completed,
	)
	return i, err
}
